apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
