apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  targetNamespace: kube-system
  releaseName: sealed-secrets
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: infrastructure
  values:
    fullnameOverride: "sealed-secrets-controller"
    namespace: "kube-system"
    image:
      repository: "bitnami/sealed-secrets-controller"
      tag: v0.19.1
    keyrenewperiod: "0"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace

