apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sql-server-sa
  namespace: mapdoon
spec:
  encryptedData:
    sa-password: AgDJ3rpv63V6TMZNApa69fx7GXqKg0ouY9kP2XUbLU48LUEnL6i8mB2wmChuIymdWJK3BJ+yUSZfDZABZs/CoK1kmIxODoUvVJLwh3gg8TCj6z0/Halua7jqVxKtO2caTtNW1rwgTMcz9lv6NXQWWI0cuOe1UxD5+1ROIXVMAiS1WrkfSfyewf/8FFhe63nT4Yb1Q9pDC8exrcqMB9aDq0hCIwbnIRg7HiHfIxeV1BbjV66K87e1/98Po/8M88S9sfitVLjXmT38aPT+70HaO7FHrr0kCbW96UXjJ3mF1tKp1WinlJeA5gouLenYUhZTmsqK3lPS+qimnn365rN+0CexNkkVZPgR2c+6Pg4r1mi6LNVP1hVOzVOKKaB64eptCXsvnUZ2BAYLgP9OyhNC+pIplCif0lza2R3oB2JGyzoT7ZfvKAf5xoQees5wL4LGFbvh5UI6j9MucO0+hPHtuxYQecXykIen1RNr+xZFjVUMAKcVtifx9sp0NQCZ2KzI+avJRE6DeS3KhDAVk/DXayN9OvduMrwPmwoGQks80klIcoqb9Pfva4gyCOvjrMCgvnLJRMuVfF2s9DDLNnSn6msZGNUmgg/k08W9JY587q58YU603/+9mBniZGwLQ5nTqLFN6HyzAvsHLrow3vlMY66et9wGV8Gel8IZalP6L/9Oc5MZH/v+W64doUrRSVQtL0wMG8+VCx/LEHro9RiRxcqaho1ClQw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sql-server-sa
      namespace: mapdoon