apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-seq
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/mapdoon/seq/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-seq
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
