apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seq
  namespace: infrastructure
spec:
  interval: 15m
  targetNamespace: infrastructure
  releaseName: seq
  chart:
    spec:
      chart: ./arvan/infrastructure/seq/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
      reconcileStrategy: Revision