apiVersion: v1
kind: PersistentVolume
metadata:
  name: mapdoon-rabbitmq
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/mapdoon/rabbitmq/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mapdoon-rabbitmq
  namespace: mapdoon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
