apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: mapdoon
spec:
  interval: 10m
  targetNamespace: mapdoon
  releaseName: rabbitmq
  chart:
    spec:
      chart: ./arvan/appdoon/mapdoon/rabbitmq/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
      reconcileStrategy: Revision
