apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mapdoon
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      name: server
      port: 9000
      targetPort: 9000
      nodePort: 31900
    - protocol: TCP
      name: console
      port: 9001
      targetPort: 9001
      nodePort: 31901