---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: appdoon-repo
  namespace: mapdoon
spec:
  image: ghcr.io/sharyash81/appdoon
  interval: 1m0s
  secretRef:
    name: ghcr.io.secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: appdoon
  namespace: mapdoon
spec:
  imageRepositoryRef:
    name: appdoon-repo
  filterTags:
    pattern: ^main-(\d+)$
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: appdoon
  namespace: mapdoon
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./arvan/appdoon/mapdoon/
    strategy: Setters