apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mapdoon-rabbitmq
  namespace: mapdoon
spec:
  interval: 1m
  path: ./arvan/appdoon/mapdoon/rabbitmq
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
