apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdoon
  namespace: appdoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdoon
  template:
    metadata:
      labels:
        app: appdoon
    spec:
      containers:
        - name: appdoon
          image: appdoon:v1
          imagePullPolicy: "Never"
          ports:
            - containerPort: 5000
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-auth
                key: access
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-auth
                key: secret   
          envFrom:
            - configMapRef:
                name: appdoon-config
