apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdoon
  namespace: appdoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdoon
  template:
    metadata:
      labels:
        app: appdoon
    spec:
      imagePullSecrets:
      - name: ghcr.io.secret
      containers:
      - name: appdoon
        image: ghcr.io/sharyash81/appdoon:main-27 # {"$imagepolicy": "mapdoon:appdoon"}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: access
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: secret
        envFrom:
        - configMapRef:
            name: appdoon-config
