apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ghcr.io.secret
  namespace: mapdoon
spec:
  encryptedData:
    .dockerconfigjson: AgBUsGauQEjvUnH7KklKhaZkaSFlE68bghDINq1mijcTnURySaGDLAQws+RbKIo2IsI9D3iaJqSkpkAY+dfjqTNs3qbYU+avWXFwmvbArICUnbD4VrcFA2wMzL9avAbqk6lO7Fv4M5YgGRikmhxkpT7pjZDX0IFDA3BhTN3gXGxJjGV0pekNVTdwnIBPkUHAjOcJvrTYYK2VrKoNR7D+2EPts+VoQOFNLPlD2NWWKFnidwMra1M6A78j1DTuUB7R2eL84JGOeet/mYHzA95IzeLlTTnhTGUTUsziwGvbGH6W9LTcbp5xZQb8VD7Oa9veNPfCR0HgGdLNR0q0ww/w1YuWyP/KioBjOf5Ialmv4ZwUG3Mpwo4DAFYoCihcqNcTh+M+JceNfxseTU76iIjLnyi1vozn0nRNFyJXASmtIV/zlSg9paum9jWWU5iCVfCRVZV17s7+6sF5CXGKwyDULaX5VNTjztyTt0vbwAO1b4Y1OlKQDq7zmqDxr3BvE2MVC+/OEQQOzCkzSNCjospbvv/sKTiBnyrlXLhPem3ADFGe5x2QRiCzlNmJ8GcRDZeZwgsamMGm9vM6Jj0U8MCq0sd7QS7b0f6Qy0XFtVst5E+lz7HjLyNUYy972ImulnfcXlg4KJ2k3NFt29BmgtDutw64Q0aF06wmeMm10urS53oP+b0yYZ9sY5KsIDKgBNhdWQJg8EEvIb24zdW1fzzNNz7WPGtGiUG4h0KIfJJOn3UYYPrwmLuo1DOofKW8jS1k9//BNM3ycoZuOZJOoy/9JJQbvMSaMwD+0rINgvJJwu/rdnyALg5y7uR3sStaClzs2fvZ6pOoCpRrG20Nciw19G3E/f8ei1iErA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ghcr.io.secret
      namespace: mapdoon
    type: kubernetes.io/dockerconfigjson